steps:
  - id: Build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --no-cache
      - -t
      - $_AR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME/$_SERVICE_NAME:latest
      - -t
      - $_AR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - -t
      - $_AR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME/$_SERVICE_NAME:$REF_NAME
      - .
      - -f
      - Dockerfile
  - id: Push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - --all-tags
      - $_AR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME/$_SERVICE_NAME
images:
  - $_AR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME/$_SERVICE_NAME:$COMMIT_SHA
  - $_AR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME/$_SERVICE_NAME:latest
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true
substitutions:
  _AR_HOSTNAME: ${_REGION}-docker.pkg.dev
tags:
  - $_SERVICE_NAME
